Available for standby controller acts as Active/Non-Optimized on array version 0.4 or later. Added starshowconfig and starsetconfig to configure it.

diff --git a/starcli b/starcli
--- a/starcli
+++ b/starcli
@@ -5,9 +5,10 @@ then
   exec sudo $0 "$@"
 fi
 
-CLI_VERSION="0.3"
+CLI_VERSION="0.4"
 
 STAR_DIR="/etc/star"
+ARRAY_VERSION=$(cat $STAR_DIR/version)
 
 AVAILABLE_COMMAND=()
 AVAILABLE_COMMAND+=("starcreatelun lun_name lun_size")
@@ -19,34 +20,23 @@ AVAILABLE_COMMAND+=("stardetachlun host_name lun_name1[,lun_name2 ...] [-nop]")
 AVAILABLE_COMMAND+=("starlistlun")
 AVAILABLE_COMMAND+=("starlisthost")
 AVAILABLE_COMMAND+=("starshowpool")
-AVAILABLE_COMMAND+=("shootingstar   # Run 'pcs resource move' command.")
-AVAILABLE_COMMAND+=("stargazing     # Run 'pcs status' command.")
-AVAILABLE_COMMAND+=("starupdatetarget")
-AVAILABLE_COMMAND+=("stargetactive")
+AVAILABLE_COMMAND+=("shootingstar       # Run 'pcs resource move' command.")
+AVAILABLE_COMMAND+=("stargazing         # Run 'pcs status' command.")
+AVAILABLE_COMMAND+=("starupdatetarget   # Update iSCSI target according to definitions.")
+AVAILABLE_COMMAND+=("stargetactive      # Return active controller name.")
+AVAILABLE_COMMAND+=("starshowconfig")
+AVAILABLE_COMMAND+=("starsetconfig variable1=value1[,variable2=value2 ...]")
 
 POOL_NAME=${POOL_NAME:-STARpool}
 
-NODE_NAME=`uname -n`
+NODE_NAME=$(uname -n)
 NODE_BASENAME=${NODE_NAME/%?/}
 NODE_NUM=${NODE_NAME: -1}
-
-if [ $NODE_NUM -eq 1 ];
-then
-  PARTNER_NODE="${NODE_BASENAME}2"
-else
-  PARTNER_NODE="${NODE_BASENAME}1"
-fi
+PARTNER_NODE="${NODE_BASENAME}$(( 3 - $NODE_NUM ))"
 
 is_active_node()
 {
-  AVAILABLE_VGS=`vgs --noheadings | wc -l`
-
-  if [ $AVAILABLE_VGS -gt 0 ]
-  then
-    return 0
-  else
-    return 1
-  fi
+  pcs resource status STARpool | egrep -q "Started +$(uname -n)"
 }
 
 check_active_node()
@@ -54,6 +44,15 @@ check_active_node()
   is_active_node && return 0
 
   echo "This command must be run on active controller."
+  exit 1
+}
+
+check_all_nodes_online()
+{
+  pcs status nodes | grep 'Online:' | grep $NODE_NAME | grep -q $PARTNER_NODE \
+      && return 0
+
+  echo "There are offline nodes."
   exit 1
 }
 
@@ -85,7 +84,7 @@ starcli()
 
   for I in $(seq 0 $(( ${#AVAILABLE_COMMAND[@]} - 1 )))
   do
-    LINK_NAME=`echo ${AVAILABLE_COMMAND[$I]} | awk '{ print $1 }'`
+    LINK_NAME=$(echo ${AVAILABLE_COMMAND[$I]} | awk '{ print $1 }')
     ( cd /usr/bin ; test -L $LINK_NAME || ln -s starcli $LINK_NAME )
 
     echo "  ${AVAILABLE_COMMAND[$I]}"
@@ -98,6 +97,7 @@ starcreatelun()
   LUN_SIZE=$2
 
   check_active_node
+  check_all_nodes_online
 
   grep -qw "$LUN_NAME" $STAR_DIR/lunlist \
       && { echo "$LUN_NAME is already exists." ; exit 1 ; }
@@ -108,7 +108,7 @@ starcreatelun()
   echo "$LUN_SIZE" | grep -qE '^[0-9]+M$' \
       || { echo "lun_size must be in megabytes, like '1024M'." ; exit 1 ; }
 
-  LUN_WWN=`uuidgen`
+  LUN_WWN=$(uuidgen)
 
   lvcreate -n $LUN_NAME -L $LUN_SIZE $POOL_NAME \
       || { echo "Failed to create ${LUN_NAME}." ; exit 1 ; }
@@ -131,6 +131,7 @@ stardeletelun()
   fi
 
   check_active_node
+  check_all_nodes_online
 
   grep -qw "$LUN_NAME" $STAR_DIR/lunlist \
       || { echo "$LUN_NAME is not exists." ; exit 1 ; }
@@ -138,7 +139,7 @@ stardeletelun()
   grep -qw "$LUN_NAME" $STAR_DIR/hostlist \
       && { echo "Cannot delete $LUN_NAME, the lun belongs to hosts." ; exit 1 ; }
 
-  NUM_LVS=`lvs --noheadings | wc -l`
+  NUM_LVS=$(lvs --noheadings | wc -l)
   if [ $NUM_LVS -eq 1 ]
   then
     echo "Cannot delete $LUN_NAME, there must be at least 1 existing LV."
@@ -156,6 +157,32 @@ stardeletelun()
   echo "$LUN_NAME deleted."
 }
 
+version() { echo "$@" | awk -F. '{ printf("%03d%03d%03d\n",$1,$2,$3); }' ; }
+
+create_tgt_port_grp()
+{
+  if [ $(version "$ARRAY_VERSION") -ge $(version "0.4") ]
+  then
+    targetcli ls /backstores/block/STAR-${LUN_NAME}/alua \
+        | grep -q 'node._tg_pt_gp' \
+            || targetcli /backstores/block/STAR-${LUN_NAME}/alua create \
+                node${NODE_NUM}_tg_pt_gp ${NODE_NUM}
+  fi
+}
+
+set_alua_tgt_port_grp()
+{
+  if [ $(version "$ARRAY_VERSION") -ge $(version "0.4") ]
+  then
+    targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/luns | grep -w STAR-${LUN_NAME} \
+        | grep -q 'node._tg_pt_gp' || {
+          lunN=$(targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/luns \
+              | awk "/STAR-${LUN_NAME}/{ print \$2 }")
+          targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/luns/$lunN \
+              set alua alua_tg_pt_gp_name=node${NODE_NUM}_tg_pt_gp ; }
+  fi
+}
+
 starupdatetarget()
 {
   WORKDIR=$(mktemp -d --tmpdir ${COMMAND_NAME}.XXXXXX)
@@ -165,13 +192,13 @@ starupdatetarget()
   ##
   OLD_IFS=$IFS
   IFS=$'\n'
-  for LUN_INFO in `cat $STAR_DIR/lunlist`
+  for LUN_INFO in $(cat $STAR_DIR/lunlist)
   do
-    LUN_NAME=`echo $LUN_INFO | awk '{ print $1 }'`
-    LUN_WWN=`echo $LUN_INFO | awk '{ print $2 }'`
+    LUN_NAME=$(echo $LUN_INFO | awk '{ print $1 }')
+    LUN_WWN=$(echo $LUN_INFO | awk '{ print $2 }')
 
     targetcli_ls -c /backstores/block 1 | grep -wq STAR-${LUN_NAME} \
-        && continue
+        && { create_tgt_port_grp ; continue ; }
 
     if is_active_node
     then
@@ -180,12 +207,12 @@ starupdatetarget()
       DEV="/dev/disk/by-id/scsi-SLIO-ORG_STAR-${LUN_NAME}_${LUN_WWN}"
       DEV_WITHOUT_WWN="/dev/disk/by-id/scsi-SLIO-ORG_STAR-${LUN_NAME}"
 
-      for OLD_DEV in `ls -1d ${DEV_WITHOUT_WWN}_* 2> /dev/null | grep -Fv ${DEV}`
+      for OLD_DEV in $(ls -1d ${DEV_WITHOUT_WWN}_* 2> /dev/null | grep -Fv ${DEV})
       do
         echo 1 > /sys/block/$(basename $(readlink $OLD_DEV))/device/delete
       done
 
-      for I in `seq 1 5`
+      for I in $(seq 1 5)
       do
 	ls -1d ${DEV_WITHOUT_WWN}_* 2> /dev/null | grep -Fv ${DEV} \
             && { sleep 1 ; continue ; }
@@ -195,12 +222,12 @@ starupdatetarget()
       iscsiadm -m discovery -t sendtargets -p $PARTNER_NODE
       iscsiadm -m node --login
 
-      for SCSI_HOST in `ls -1d /sys/class/scsi_host/host*`
+      for SCSI_HOST in $(ls -1d /sys/class/scsi_host/host*)
       do
         echo '- - -' > $SCSI_HOST/scan
       done
 
-      for I in `seq 1 5`
+      for I in $(seq 1 5)
       do
         test -L ${DEV} || { sleep 1 ; continue ; }
 	break
@@ -208,11 +235,11 @@ starupdatetarget()
     fi
 
     targetcli /backstores/block create name=STAR-${LUN_NAME} \
-        dev=${DEV} wwn=${LUN_WWN}
+        dev=${DEV} wwn=${LUN_WWN} && create_tgt_port_grp
   done
   IFS=$OLD_IFS
 
-  ARRAY_NAME=`cat $STAR_DIR/starname`
+  ARRAY_NAME=$(cat $STAR_DIR/starname)
   ARRAY_TGT_IQN="iqn.2023-09.test.use.only:${ARRAY_NAME}-target"
 
   targetcli ls /iscsi/$ARRAY_TGT_IQN > /dev/null 2>&1 \
@@ -225,16 +252,16 @@ starupdatetarget()
 
   OLD_IFS=$IFS
   IFS=$'\n'
-  for LUN_INFO in `cat $STAR_DIR/lunlist`
+  for LUN_INFO in $(cat $STAR_DIR/lunlist)
   do
-    LUN_NAME=`echo $LUN_INFO | awk '{ print $1 }'`
+    LUN_NAME=$(echo $LUN_INFO | awk '{ print $1 }')
 
     grep -qw $LUN_NAME $STAR_DIR/hostlist || continue
 
     targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/luns | grep -qw $LUN_NAME \
-        && continue
+        && { set_alua_tgt_port_grp ; continue ; }
 
-    for I in `seq 0 127`
+    for I in $(seq 0 127)
     do
       targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/luns | grep -wq lun${I} \
           || break
@@ -243,24 +270,25 @@ starupdatetarget()
     targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/luns create /backstores/block/STAR-${LUN_NAME} $I false
     targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$ARRAY_INIT_IQN create $I \
         /backstores/block/STAR-${LUN_NAME}
+    set_alua_tgt_port_grp
 
     targetcli_ls /iscsi/$ARRAY_TGT_IQN/tpg1/luns > /dev/null 2>&1
   done
 
-  for HOST_INFO in `cat $STAR_DIR/hostlist`
+  for HOST_INFO in $(cat $STAR_DIR/hostlist)
   do
-    HOST_IQN=`echo $HOST_INFO | awk '{ print $2 }'`
-    HOST_LUNS=`echo $HOST_INFO | awk '{ print $3 }'`
+    HOST_IQN=$(echo $HOST_INFO | awk '{ print $2 }')
+    HOST_LUNS=$(echo $HOST_INFO | awk '{ print $3 }')
 
     targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/acls | grep -qw $HOST_IQN \
         || targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/acls create $HOST_IQN false
 
-    for LUN_NAME in `echo $HOST_LUNS | sed 's/,/\n/g'`
+    for LUN_NAME in $(echo $HOST_LUNS | sed 's/,/\n/g')
     do
       targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$HOST_IQN | grep -qw $LUN_NAME \
           && continue
 
-      for I in `seq 0 127`
+      for I in $(seq 0 127)
       do
         targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$HOST_IQN | grep -qw mapped_lun${I} \
             || break
@@ -278,7 +306,7 @@ starupdatetarget()
   ## remove objects
   ##
   for HOST_IQN in \
-      `targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/acls 1 | grep -v -e acls -e $ARRAY_INIT_IQN | awk '{ print $2 }'`
+      $(targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/acls 1 | grep -v -e acls -e $ARRAY_INIT_IQN | awk '{ print $2 }')
   do
     grep -q "[[:blank:]]${HOST_IQN}[[:blank:]]" $STAR_DIR/hostlist \
         || { targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/acls delete $HOST_IQN ; continue ; }
@@ -329,6 +357,7 @@ starcreatehost()
   HOST_LUNS=$3
 
   check_active_node
+  check_all_nodes_online
 
   grep -qw "$HOST_NAME" $STAR_DIR/hostlist \
       && { echo "$HOST_NAME is already exists." ; exit 1 ; }  
@@ -352,6 +381,7 @@ stardeletehost()
   NOP=$2
 
   check_active_node
+  check_all_nodes_online
 
   grep -qw "$HOST_NAME" $STAR_DIR/hostlist \
       || { echo "$HOST_NAME is not exists." ; exit 1 ; }
@@ -391,19 +421,20 @@ starattachlun()
   ATTACH_LUNS=$2
 
   check_active_node
+  check_all_nodes_online
 
   grep -qw "$HOST_NAME" $STAR_DIR/hostlist \
       || { echo "$HOST_NAME is not exists." ; exit 1 ; }
 
-  for LUN_NAME in `echo $ATTACH_LUNS | sed 's/,/\n/g'`
+  for LUN_NAME in $(echo $ATTACH_LUNS | sed 's/,/\n/g')
   do
     grep -w "$HOST_NAME" $STAR_DIR/hostlist | grep -qw $LUN_NAME \
         && { echo "$LUN_NAME is already belongs to ${HOST_NAME}." ; exit 1 ; }
   done
 
-  HOST_INFO=`grep -w $HOST_NAME $STAR_DIR/hostlist`
-  HOST_IQN=`echo $HOST_INFO | awk '{ print $2 }'`
-  HOST_LUNS=`echo $HOST_INFO | awk '{ print $3 }'`
+  HOST_INFO=$(grep -w $HOST_NAME $STAR_DIR/hostlist)
+  HOST_IQN=$(echo $HOST_INFO | awk '{ print $2 }')
+  HOST_LUNS=$(echo $HOST_INFO | awk '{ print $3 }')
 
   if [ -z "$HOST_LUNS" ]
   then
@@ -433,11 +464,12 @@ stardetachlun()
   NOP=$3
 
   check_active_node
+  check_all_nodes_online
 
   grep -qw "$HOST_NAME" $STAR_DIR/hostlist \
       || { echo "$HOST_NAME is not exists." ; exit 1 ; }
 
-  for LUN_NAME in `echo $DETACH_LUNS | sed 's/,/\n/g'`
+  for LUN_NAME in $(echo $DETACH_LUNS | sed 's/,/\n/g')
   do
     grep -w "$HOST_NAME" $STAR_DIR/hostlist | grep -qw $LUN_NAME \
         || { echo "$LUN_NAME is not belongs to ${HOST_NAME}." ; exit 1 ; }
@@ -461,11 +493,11 @@ stardetachlun()
     esac
   fi
 
-  HOST_INFO=`grep -w $HOST_NAME $STAR_DIR/hostlist`
-  HOST_IQN=`echo $HOST_INFO | awk '{ print $2 }'`
-  HOST_LUNS=`echo $HOST_INFO | awk '{ print $3 }'`
+  HOST_INFO=$(grep -w $HOST_NAME $STAR_DIR/hostlist)
+  HOST_IQN=$(echo $HOST_INFO | awk '{ print $2 }')
+  HOST_LUNS=$(echo $HOST_INFO | awk '{ print $3 }')
 
-  for LUN_NAME in `echo $DETACH_LUNS | sed 's/,/\n/g'`
+  for LUN_NAME in $(echo $DETACH_LUNS | sed 's/,/\n/g')
   do
     HOST_LUNS=$(echo "${HOST_LUNS}" | sed 's/,/\n/g' | grep -vw $LUN_NAME \
         | sort | tr '\n' ',' | sed 's/,$/\n/g')
@@ -494,7 +526,28 @@ stargetactive()
   fi
 }
 
-COMMAND_NAME=`basename $0`
+starsetconfig()
+{
+  VAR_VAL_LIST=$1
+
+  check_active_node
+  check_all_nodes_online
+
+  for VAR_VAL in $(echo $VAR_VAL_LIST | sed 's/,/\n/g')
+  do
+    VAR=${VAR_VAL%=*}
+    grep -wq "$VAR" $STAR_DIR/config \
+        || { echo "Invalid variable $VAR skipped." ; continue ; }
+    echo "$VAR_VAL"
+    sed -i "s/^${VAR}=.*/$VAR_VAL/g" $STAR_DIR/config
+  done
+
+  scp $STAR_DIR/config ${PARTNER_NODE}:${STAR_DIR}
+
+  echo 'For apply in most cases, need to failover with `shootingstar` command.'
+}
+
+COMMAND_NAME=$(basename $0)
 
 case $COMMAND_NAME in
   starlistlun)
@@ -509,10 +562,14 @@ case $COMMAND_NAME in
     ;;
   shootingstar)
     check_active_node
+    check_all_nodes_online
     pcs resource move STARpool --autodelete
     ;;
   stargazing)
     pcs status
+    ;;
+  starshowconfig)
+    cat $STAR_DIR/config
     ;;
   *)
     $COMMAND_NAME "$@"
