Specify chunk size of snapshot for reduce performance degration.

diff --git a/starcli b/starcli
--- a/starcli
+++ b/starcli
@@ -49,9 +49,9 @@ AVAILABLE_COMMAND+=("stardeletehost host_name [-nop]")
 AVAILABLE_COMMAND+=("starattachlun host_name lun_or_snap_name1[,lun_or_snap_name2 ...]")
 AVAILABLE_COMMAND+=("stardetachlun host_name lun_or_snap_name1[,lun_or_snap_name2 ...] [-nop]")
 AVAILABLE_COMMAND+=("starlistsnap")
-AVAILABLE_COMMAND+=("starcreatesnap snap_name src_lun_name snap_size")
+AVAILABLE_COMMAND+=("starcreatesnap snap_name src_lun_name snap_alloc_size")
 AVAILABLE_COMMAND+=("starrecreatesnap snap_name [-nop]")
-AVAILABLE_COMMAND+=("starextendsnap snap_name snap_size [-nop]")
+AVAILABLE_COMMAND+=("starextendsnap snap_name snap_alloc_size [-nop]")
 AVAILABLE_COMMAND+=("starrestoresnap snap_name [-nop]")
 AVAILABLE_COMMAND+=("stardeletesnap snap_name [-nop]")
 AVAILABLE_COMMAND+=("staractivatelun lun_or_snap_name1[,lun_or_snap_name2 ...]")
@@ -755,7 +755,7 @@ starcreatesnap()
 {
   SNAP_NAME=$1
   SOURCE_LUN_NAME=$2
-  SNAP_SIZE=$3
+  SNAP_ALLOC_SIZE=$3
 
   check_active_node
   check_all_nodes_online
@@ -769,28 +769,29 @@ starcreatesnap()
   echo "$SNAP_NAME" | grep -qE '^SNAP[0-9]+$' \
       || { echo "snap_name must be match pettern '^SNAP[0-9]+'." ; exit 1 ; }
 
-  echo "$SNAP_SIZE" | grep -qE -e '^[0-9]+M$' -e '^[1-9][0-9]*%ORIGIN$' \
-      || { echo "snap_size must be in megabytes, like '1024M'." ;
+  echo "$SNAP_ALLOC_SIZE" | grep -qE -e '^[0-9]+M$' -e '^[1-9][0-9]*%ORIGIN$' \
+      || { echo "snap_alloc_size must be in megabytes, like '1024M'." ;
            echo "  or percentage(of source lun size)%ORIGIN format, like '10%ORIGIN'." ;
 	   exit 1 ; }
 
   SNAP_WWN=$(uuidgen)
 
-  if echo "$SNAP_SIZE" | grep -qE '^[0-9]+M$'
+  if echo "$SNAP_ALLOC_SIZE" | grep -qE '^[0-9]+M$'
   then
     OPT="-L"
   else
     OPT="-l"
   fi
 
-  lvcreate -n $SNAP_NAME $OPT $SNAP_SIZE --snapshot /dev/$POOL_NAME/$SOURCE_LUN_NAME \
-      || { echo "Failed to create ${SNAP_NAME}." ; exit 1 ; }
+  lvcreate -n $SNAP_NAME $OPT $SNAP_ALLOC_SIZE -c ${SNAP_CHUNK_SIZE:-256} --snapshot \
+      /dev/$POOL_NAME/$SOURCE_LUN_NAME \
+          || { echo "Failed to create ${SNAP_NAME}." ; exit 1 ; }
 
-  echo "$SNAP_NAME $SOURCE_LUN_NAME $SNAP_WWN $SNAP_SIZE" >> $STAR_DIR/snaplist
+  echo "$SNAP_NAME $SOURCE_LUN_NAME $SNAP_WWN $SNAP_ALLOC_SIZE" >> $STAR_DIR/snaplist
   
   scp $STAR_DIR/snaplist ${PARTNER_NODE}:${STAR_DIR}
 
-  echo "$SNAP_NAME $SOURCE_LUN_NAME $SNAP_WWN $SNAP_SIZE"
+  echo "$SNAP_NAME $SOURCE_LUN_NAME $SNAP_WWN $SNAP_ALLOC_SIZE"
 }
 
 starrecreatesnap()
@@ -817,9 +818,9 @@ starrecreatesnap()
   SNAP_INFO=$(grep -w "^$SNAP_NAME" $STAR_DIR/snaplist)
   SOURCE_LUN_NAME=$(echo $SNAP_INFO | awk '{ print $2 }')
   SNAP_WWN=$(echo $SNAP_INFO | awk '{ print $3 }')
-  SNAP_SIZE=$(echo $SNAP_INFO | awk '{ print $4 }')
+  SNAP_ALLOC_SIZE=$(echo $SNAP_INFO | awk '{ print $4 }')
 
-  if echo "$SNAP_SIZE" | grep -qE '^[0-9]+M$'
+  if echo "$SNAP_ALLOC_SIZE" | grep -qE '^[0-9]+M$'
   then
     OPT="-L"
   else
@@ -829,7 +830,9 @@ starrecreatesnap()
   lvremove -y /dev/$POOL_NAME/$SNAP_NAME \
       || { echo "Failed to delete ${SNAP_NAME}." ; exit 1 ; }
 
-  lvcreate -n $SNAP_NAME $OPT $SNAP_SIZE --snapshot /dev/$POOL_NAME/$SOURCE_LUN_NAME
+  lvcreate -n $SNAP_NAME $OPT $SNAP_ALLOC_SIZE -c ${SNAP_CHUNK_SIZE:-256} --snapshot \
+      /dev/$POOL_NAME/$SOURCE_LUN_NAME \
+          || { echo "Failed to create ${SNAP_NAME}." ; exit 1 ; }
 
   if [ $IS_DEACTIVATED -eq 0 ]
   then
@@ -842,7 +845,7 @@ starrecreatesnap()
 starextendsnap()
 {
   SNAP_NAME=$1
-  NEW_SNAP_SIZE=$2
+  NEW_SNAP_ALLOC_SIZE=$2
   NOP=$3
 
   check_active_node
@@ -854,23 +857,23 @@ starextendsnap()
   SNAP_INFO=$(grep -w "^$SNAP_NAME" $STAR_DIR/snaplist)
   SOURCE_LUN_NAME=$(echo $SNAP_INFO | awk '{ print $2 }')
   SNAP_WWN=$(echo $SNAP_INFO | awk '{ print $3 }')
-  SNAP_SIZE=$(echo $SNAP_INFO | awk '{ print $4 }')
+  SNAP_ALLOC_SIZE=$(echo $SNAP_INFO | awk '{ print $4 }')
 
   confirm_execution \
-      "Extend $SNAP_NAME size from $SNAP_SIZE to $NEW_SNAP_SIZE?" $NOP
+      "Extend $SNAP_NAME size from $SNAP_ALLOC_SIZE to $NEW_SNAP_ALLOC_SIZE?" $NOP
 
-  if echo "$SNAP_SIZE" | grep -qE '^[0-9]+M$'
+  if echo "$SNAP_ALLOC_SIZE" | grep -qE '^[0-9]+M$'
   then
     OPT="-L"
   else
     OPT="-l"
   fi
 
-  lvextend $OPT $NEW_SNAP_SIZE /dev/$POOL_NAME/$SNAP_NAME \
+  lvextend $OPT $NEW_SNAP_ALLOC_SIZE /dev/$POOL_NAME/$SNAP_NAME \
       || { echo "Failed to extend ${SNAP_NAME}." ; exit 1 ; }
 
   sed -i -E \
-      's/^('"$SNAP_NAME"') +.+/\1 '"$SOURCE_LUN_NAME $SNAP_WWN $NEW_SNAP_SIZE"'/g' \
+      's/^('"$SNAP_NAME"') +.+/\1 '"$SOURCE_LUN_NAME $SNAP_WWN $NEW_SNAP_ALLOC_SIZE"'/g' \
           $STAR_DIR/snaplist
 
   echo "$SNAP_NAME extended."
